planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/kp2/joint_states"
  attached_collision_object_topic: "/kp2/planning_scene_monitor"
  publish_planning_scene_topic: "/kp2/publish_planning_scene"
  monitored_planning_scene_topic: "/kp2/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  pipeline_names:
    - ompl

default_planner_options:
  planning_attempts: 1
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0
